# Generated by Django 5.0.6 on 2024-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_investor_customuser_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
