# Generated by Django 4.2 on 2024-07-04 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('founding_date', models.DateField()),
                ('legal_form', models.CharField(max_length=255)),
                ('type_of_business', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('product_description', models.TextField()),
                ('customer_problem', models.TextField()),
                ('usp', models.TextField()),
                ('capital', models.FloatField()),
                ('stage', models.CharField(max_length=255)),
                ('target_investor_n', models.CharField(max_length=255)),
                ('use_of_funds', models.JSONField()),
                ('financial_tables', models.TextField()),
                ('already_invested_n', models.FloatField()),
                ('impact_value', models.FloatField()),
                ('team_values', models.JSONField()),
                ('team_motives', models.JSONField()),
                ('funding_experience', models.JSONField()),
                ('team_languages', models.JSONField()),
                ('investore_expertise', models.JSONField()),
                ('investore_expectations', models.JSONField()),
                ('exit_strategy', models.CharField(max_length=255)),
                ('type_of_investment', models.CharField(max_length=255)),
                ('market', models.TextField()),
                ('sdg', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('type_of_business', models.CharField(max_length=255)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('capital', models.CharField(max_length=255)),
                ('stage', models.JSONField()),
                ('impact_value', models.FloatField()),
                ('team_values', models.JSONField()),
                ('team_motives', models.JSONField()),
                ('languages', models.JSONField()),
                ('investor_expertise', models.JSONField()),
                ('investor_value', models.JSONField()),
                ('exit_strategy', models.CharField(max_length=255)),
                ('type_of_investment', models.CharField(max_length=255)),
                ('market', models.TextField()),
                ('sdg', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
