# Generated by Django 5.0.6 on 2024-07-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_investor_user_alter_startup_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='investore_expectations',
            new_name='investor_expectations',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='investore_expertise',
            new_name='investor_expertise',
        ),
    ]
