# Generated by Django 5.0.6 on 2024-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_investore_expectations_startup_investor_expectations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_offering',
            field=models.JSONField(default=''),
        ),
    ]
