# Generated by Django 5.0.6 on 2024-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_investor_investor_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='capital',
            field=models.JSONField(),
        ),
    ]
