# Generated by Django 5.0.6 on 2024-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_investor_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='capital',
            field=models.FloatField(),
        ),
    ]
