import json
from django.core.management.base import BaseCommand
from django.utils.timezone import now
from django.contrib.auth import get_user_model
from api.models import Startup

class Command(BaseCommand):
    help = 'Initialize startup models with meaningful values'

    def handle(self, *args, **options):
        # Ensure there is at least one user to assign as the creator of the startups
        User = get_user_model()
        if not User.objects.exists():
            self.stdout.write(self.style.ERROR('No users found in the database. Create at least one user before running this script.'))
            return

        user = User.objects.first()

        startups_data = [
            {
                "name": "Tech Innovators",
                "code": "TI001",
                "location": "San Francisco, CA",
                "industry": "Technology",
                "founding_date": "2020-01-01",
                "legal_form": "LLC",
                "type_of_business": "Software Development",
                "website": "https://techinnovators.com",
                "facebook": "https://facebook.com/techinnovators",
                "linkedin": "https://linkedin.com/company/techinnovators",
                "twitter": "https://twitter.com/techinnovators",
                "description": "Innovative tech solutions for modern problems.",
                "mission": "To revolutionize technology.",
                "product_description": "Cutting-edge software solutions.",
                "customer_problem": "Need for advanced tech solutions.",
                "usp": "Unique tech innovations.",
                "capital": 1000000.0,
                "stage": "Seed",
                "target_investor_n": "Angel Investors",
                "use_of_funds": {"R&D": 500000, "Marketing": 300000, "Operations": 200000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 200000.0,
                "impact_value": 8.5,
                "team_values": {"integrity": "high", "innovation": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "none"},
                "team_languages": {"english": "fluent", "spanish": "basic"},
                "investore_expertise": {"tech": "high", "business": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "low"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global tech market.",
                "sdg": {"goal1": "No Poverty", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            # Add 4 more startup dictionaries here with similar structure
            # ...
            {
                "user": 2,
                "name": "Green Energy Solutions",
                "code": "GES002",
                "location": "Austin, TX",
                "industry": "Renewable Energy",
                "founding_date": "2018-05-10",
                "legal_form": "Corporation",
                "type_of_business": "Energy Production",
                "website": "https://greenenergysolutions.com",
                "facebook": "",
                "linkedin": "https://linkedin.com/company/greenenergysolutions",
                "twitter": "",
                "description": "Providing sustainable energy solutions.",
                "mission": "To lead the transition to renewable energy.",
                "product_description": "Solar and wind energy products.",
                "customer_problem": "Dependence on fossil fuels.",
                "usp": "Clean and affordable energy.",
                "capital": 5000000.0,
                "stage": "Series A",
                "target_investor_n": "Venture Capitalists",
                "use_of_funds": {"Infrastructure": 3000000, "R&D": 1500000, "Marketing": 500000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 1000000.0,
                "impact_value": 9.2,
                "team_values": {"sustainability": "high", "innovation": "medium"},
                "team_motives": {"environment": "high", "growth": "medium"},
                "funding_experience": {"seed": "experienced", "series_a": "experienced"},
                "team_languages": {"english": "fluent", "french": "basic"},
                "investore_expertise": {"energy": "high", "sustainability": "high"},
                "investore_expectations": {"returns": "medium", "involvement": "medium"},
                "exit_strategy": "IPO",
                "type_of_investment": "Equity",
                "market": "Global renewable energy market.",
                "sdg": {"goal7": "Affordable and Clean Energy", "goal13": "Climate Action"},
            },
            {
                "user": 3,
                "name": "HealthTech Pioneers",
                "code": "HTP003",
                "location": "Boston, MA",
                "industry": "Healthcare",
                "founding_date": "2019-09-15",
                "legal_form": "Corporation",
                "type_of_business": "Medical Devices",
                "website": "https://healthtechpioneers.com",
                "facebook": "https://facebook.com/healthtechpioneers",
                "linkedin": "",
                "twitter": "https://twitter.com/healthtechpioneers",
                "description": "Innovative healthcare technology.",
                "mission": "To improve patient outcomes through technology.",
                "product_description": "Advanced medical devices.",
                "customer_problem": "Need for better healthcare tools.",
                "usp": "State-of-the-art technology.",
                "capital": 2000000.0,
                "stage": "Seed",
                "target_investor_n": "Angel Investors",
                "use_of_funds": {"R&D": 1200000, "Clinical Trials": 500000, "Marketing": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 500000.0,
                "impact_value": 8.8,
                "team_values": {"integrity": "high", "innovation": "high"},
                "team_motives": {"patient care": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "none"},
                "team_languages": {"english": "fluent", "mandarin": "basic"},
                "investore_expertise": {"healthcare": "high", "technology": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "medium"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global healthcare market.",
                "sdg": {"goal3": "Good Health and Well-being", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            {
                "user": 4,
                "name": "Eco-Friendly Packaging",
                "code": "EFP004",
                "location": "Seattle, WA",
                "industry": "Manufacturing",
                "founding_date": "2017-04-22",
                "legal_form": "LLC",
                "type_of_business": "Packaging Solutions",
                "website": "https://ecofriendlypackaging.com",
                "facebook": "https://facebook.com/ecofriendlypackaging",
                "linkedin": "https://linkedin.com/company/ecofriendlypackaging",
                "twitter": "https://twitter.com/ecofriendlypack",
                "description": "Sustainable packaging solutions.",
                "mission": "To reduce plastic waste.",
                "product_description": "Biodegradable packaging.",
                "customer_problem": "Environmental impact of packaging waste.",
                "usp": "Eco-friendly and cost-effective.",
                "capital": 3000000.0,
                "stage": "Series B",
                "target_investor_n": "Venture Capitalists",
                "use_of_funds": {"Production": 2000000, "R&D": 700000, "Marketing": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 1500000.0,
                "impact_value": 9.0,
                "team_values": {"sustainability": "high", "innovation": "medium"},
                "team_motives": {"environment": "high", "growth": "medium"},
                "funding_experience": {"seed": "experienced", "series_a": "experienced"},
                "team_languages": {"english": "fluent", "spanish": "basic"},
                "investore_expertise": {"manufacturing": "high", "sustainability": "high"},
                "investore_expectations": {"returns": "medium", "involvement": "medium"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global packaging market.",
                "sdg": {"goal12": "Responsible Consumption and Production", "goal13": "Climate Action"},
            },
            {
                "user": 5,
                "name": "FinTech Innovators",
                "code": "FI005",
                "location": "New York, NY",
                "industry": "Financial Technology",
                "founding_date": "2021-11-01",
                "legal_form": "Corporation",
                "type_of_business": "FinTech Solutions",
                "website": "https://fintechinnovators.com",
                "facebook": "https://facebook.com/fintechinnovators",
                "linkedin": "https://linkedin.com/company/fintechinnovators",
                "twitter": "https://twitter.com/fintechinnovate",
                "description": "Revolutionizing financial services.",
                "mission": "To democratize finance through technology.",
                "product_description": "Innovative financial solutions.",
                "customer_problem": "Need for better financial tools.",
                "usp": "User-friendly and secure.",
                "capital": 1500000.0,
                "stage": "Seed",
                "target_investor_n": "Angel Investors",
                "use_of_funds": {"R&D": 800000, "Marketing": 500000, "Operations": 200000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 300000.0,
                "impact_value": 8.7,
                "team_values": {"integrity": "high", "innovation": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "none"},
                "team_languages": {"english": "fluent", "german": "basic"},
                "investore_expertise": {"fintech": "high", "business": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "low"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global fintech market.",
                "sdg": {"goal8": "Decent Work and Economic Growth", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            {
                "user": 6,
                "name": "EdTech Revolution",
                "code": "ET006",
                "location": "Los Angeles, CA",
                "industry": "Education Technology",
                "founding_date": "2019-02-14",
                "legal_form": "Corporation",
                "type_of_business": "Online Education",
                "website": "https://edtechrevolution.com",
                "facebook": "https://facebook.com/edtechrevolution",
                "linkedin": "https://linkedin.com/company/edtechrevolution",
                "twitter": "https://twitter.com/edtechrev",
                "description": "Transforming education through technology.",
                "mission": "To make quality education accessible to all.",
                "product_description": "Online learning platforms.",
                "customer_problem": "Lack of access to quality education.",
                "usp": "Accessible and engaging learning.",
                "capital": 2500000.0,
                "stage": "Series A",
                "target_investor_n": "Venture Capitalists",
                "use_of_funds": {"Platform Development": 1500000, "Marketing": 700000, "Operations": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 500000.0,
                "impact_value": 9.1,
                "team_values": {"education": "high", "innovation": "high"},
                "team_motives": {"learning": "high", "growth": "medium"},
                "funding_experience": {"seed": "experienced", "series_a": "experienced"},
                "team_languages": {"english": "fluent", "french": "basic"},
                "investore_expertise": {"education": "high", "technology": "medium"},
                "investore_expectations": {"returns": "medium", "involvement": "medium"},
                "exit_strategy": "IPO",
                "type_of_investment": "Equity",
                "market": "Global education market.",
                "sdg": {"goal4": "Quality Education", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            {
                "user": 7,
                "name": "AgriTech Innovations",
                "code": "ATI007",
                "location": "Des Moines, IA",
                "industry": "Agriculture Technology",
                "founding_date": "2020-08-01",
                "legal_form": "LLC",
                "type_of_business": "Smart Farming",
                "website": "https://agritechinnovations.com",
                "facebook": "https://facebook.com/agritechinnovations",
                "linkedin": "https://linkedin.com/company/agritechinnovations",
                "twitter": "https://twitter.com/agritechinnovate",
                "description": "Next-gen farming solutions.",
                "mission": "To enhance agricultural productivity through technology.",
                "product_description": "Smart farming tools.",
                "customer_problem": "Need for more efficient farming methods.",
                "usp": "Innovative and efficient.",
                "capital": 2000000.0,
                "stage": "Seed",
                "target_investor_n": "Angel Investors",
                "use_of_funds": {"R&D": 1200000, "Marketing": 500000, "Operations": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 400000.0,
                "impact_value": 8.6,
                "team_values": {"sustainability": "high", "innovation": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "none"},
                "team_languages": {"english": "fluent", "spanish": "basic"},
                "investore_expertise": {"agriculture": "high", "technology": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "low"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global agriculture market.",
                "sdg": {"goal2": "Zero Hunger", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            {
                "user": 8,
                "name": "Smart Home Solutions",
                "code": "SHS008",
                "location": "San Jose, CA",
                "industry": "Smart Home Technology",
                "founding_date": "2021-06-30",
                "legal_form": "Corporation",
                "type_of_business": "Home Automation",
                "website": "https://smarthomesolutions.com",
                "facebook": "https://facebook.com/smarthomesolutions",
                "linkedin": "https://linkedin.com/company/smarthomesolutions",
                "twitter": "https://twitter.com/smarthomesol",
                "description": "Smart solutions for modern homes.",
                "mission": "To make homes smarter and more efficient.",
                "product_description": "Home automation systems.",
                "customer_problem": "Need for smarter home management.",
                "usp": "Innovative and user-friendly.",
                "capital": 1800000.0,
                "stage": "Seed",
                "target_investor_n": "Angel Investors",
                "use_of_funds": {"R&D": 1000000, "Marketing": 500000, "Operations": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 300000.0,
                "impact_value": 8.4,
                "team_values": {"innovation": "high", "quality": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "none"},
                "team_languages": {"english": "fluent", "german": "basic"},
                "investore_expertise": {"technology": "high", "business": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "low"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global smart home market.",
                "sdg": {"goal9": "Industry, Innovation, and Infrastructure", "goal11": "Sustainable Cities and Communities"},
            },
            {
                "user": 9,
                "name": "BioTech Advances",
                "code": "BTA009",
                "location": "San Diego, CA",
                "industry": "Biotechnology",
                "founding_date": "2018-12-12",
                "legal_form": "Corporation",
                "type_of_business": "Biotech Research",
                "website": "https://biotechadvances.com",
                "facebook": "https://facebook.com/biotechadvances",
                "linkedin": "https://linkedin.com/company/biotechadvances",
                "twitter": "https://twitter.com/biotechadvances",
                "description": "Leading biotech research and development.",
                "mission": "To innovate and advance biotech solutions.",
                "product_description": "Advanced biotech products.",
                "customer_problem": "Need for innovative biotech solutions.",
                "usp": "Cutting-edge research.",
                "capital": 2500000.0,
                "stage": "Series A",
                "target_investor_n": "Venture Capitalists",
                "use_of_funds": {"R&D": 1500000, "Clinical Trials": 700000, "Marketing": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 800000.0,
                "impact_value": 9.3,
                "team_values": {"innovation": "high", "integrity": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "experienced"},
                "team_languages": {"english": "fluent", "japanese": "basic"},
                "investore_expertise": {"biotech": "high", "healthcare": "medium"},
                "investore_expectations": {"returns": "medium", "involvement": "medium"},
                "exit_strategy": "IPO",
                "type_of_investment": "Equity",
                "market": "Global biotech market.",
                "sdg": {"goal3": "Good Health and Well-being", "goal9": "Industry, Innovation, and Infrastructure"},
            },
            {
                "user": 10,
                "name": "Cyber Security Experts",
                "code": "CSE010",
                "location": "Washington, D.C.",
                "industry": "Cyber Security",
                "founding_date": "2020-03-03",
                "legal_form": "LLC",
                "type_of_business": "Security Solutions",
                "website": "https://cybersecurityexperts.com",
                "facebook": "https://facebook.com/cybersecurityexperts",
                "linkedin": "https://linkedin.com/company/cybersecurityexperts",
                "twitter": "https://twitter.com/cybersecexperts",
                "description": "Protecting digital assets.",
                "mission": "To provide top-tier cyber security.",
                "product_description": "Advanced security systems.",
                "customer_problem": "Rising cyber threats.",
                "usp": "Unmatched security solutions.",
                "capital": 3000000.0,
                "stage": "Series B",
                "target_investor_n": "Venture Capitalists",
                "use_of_funds": {"R&D": 2000000, "Marketing": 700000, "Operations": 300000},
                "financial_tables": "Financial data here.",
                "already_invested_n": 1000000.0,
                "impact_value": 9.5,
                "team_values": {"integrity": "high", "security": "high"},
                "team_motives": {"growth": "high", "success": "high"},
                "funding_experience": {"seed": "experienced", "series_a": "experienced"},
                "team_languages": {"english": "fluent", "russian": "basic"},
                "investore_expertise": {"security": "high", "technology": "medium"},
                "investore_expectations": {"returns": "high", "involvement": "medium"},
                "exit_strategy": "Acquisition",
                "type_of_investment": "Equity",
                "market": "Global cyber security market.",
                "sdg": {"goal9": "Industry, Innovation, and Infrastructure", "goal16": "Peace, Justice, and Strong Institutions"},
            }
        ]

        for startup_data in startups_data:
            Startup.objects.create(
                user=user,
                **startup_data
            )

        self.stdout.write(self.style.SUCCESS('Successfully initialized startup models.'))