# Generated by Django 5.0.6 on 2024-07-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_investor_user_alter_startup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.investor')),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.startup')),
            ],
        ),
    ]
