# Generated by Django 5.0.6 on 2024-08-08 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='startup',
        ),
        migrations.AddField(
            model_name='matching',
            name='investor_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='investor_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='startup_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='startup_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
