# Generated by Django 4.2 on 2024-08-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matcher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='investor_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='startup_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
