# Generated by Django 5.0.6 on 2024-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_remove_matching_investor_remove_matching_startup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='investor_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matching',
            name='startup_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
